"""empty message

Revision ID: 5e94fce6ccb5
Revises: b25cec47c0b2
Create Date: 2018-02-20 08:51:56.312497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e94fce6ccb5'
down_revision = 'b25cec47c0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_log', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_log', 'date')
    # ### end Alembic commands ###
