"""empty message

Revision ID: b25cec47c0b2
Revises: bea5df2fe549
Create Date: 2018-02-19 19:20:35.611050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25cec47c0b2'
down_revision = 'bea5df2fe549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('a', sa.String(length=255), nullable=True))
    op.add_column('blacklist', sa.Column('aaaa', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklist', 'aaaa')
    op.drop_column('blacklist', 'a')
    # ### end Alembic commands ###
