"""empty message

Revision ID: bea5df2fe549
Create Date: 2018-02-19 15:48:33.145486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea5df2fe549'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('redirects_to', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklist', 'redirects_to')
    # ### end Alembic commands ###
